---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrics-sample-app
  template:
    metadata:
      labels:
        app: metrics-sample-app
    spec:
      containers:
        - name: webserver-simple
          image: nginx
          ports:
            - containerPort: 8080
