apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-webserver
  template:
    metadata:
      labels:
        app: sample-webserver
    spec:
      containers:
        - name: webserver-simple
          image: nginx
          ports:
            - containerPort: 8080
