apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-metrics-app
  template:
    metadata:
      labels:
        app: sample-metrics-app
    spec:
      containers:
        - name: webserver-simple
          image: docker.io/trathi1526/metrics-app-image
          ports:
            - containerPort: 8080
